project:
  type: website

website:
  title: "Andrew Belz- Data Science Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: resume.qmd
        text: My Resume

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



