

# ANDREW BELZ

<div class='resume-contact'>
<a href="https://github.com/pbelz1" target="_blank">GitHub</a>
<a href="https://www.linkedin.com/in/andrewbelz/" target="_blank">LinkedIn</a>
<a href='mailto:andrewbelzjr@gmail.com' target='_blank'>andrewbelzjr@gmail.com</a>
<a href='tel:+18056244436' target='_blank'>(805) 624-4436</a>
</div>

---

Passionate aspiring data scientist always looking for new challenges. Technically adept, with both mathematical and programming skills in statistics, Python, R, and SQL. Flexible and hard-working team player.

---

### Project Experience Highlights

<a href='project_files/inequality_analysis.html' class='resume-project-link'><h4>Socioeconomic Inequality Statistical Analysis</h4></a>

Analysis Project using R: Uncovered trends in poverty and race in relation to crime rates using official US Census data. Showcased abilities in hypothesis testing, linear regression, ANOVA, model validation, API data extraction, exploratory data analysis, and data visualization (ggplot).

<h4>Stock Price Tracking Application</h4>

Python Application: implemented and automated ETL process to retrieve data from Yahoo Finance API via yfinance python module, appropriately transforming resulting data with pandas, and loading resulting data frame into a Plotly Dash app graphically and tabularly: Showcase abilities with Python, Dash, Plotly, Pandas, yfinance, HTML, and CSS.

---

### Education
Bachelor of Science in Data Science - Brigham Young University-Idaho\
4.0 GPA\
Relevant Coursework: Data Science Programming, Intermediate Statistics, Introduction to Databases 

---

### Work Experience

#### Solar Technician
Mitchell Security, Inc., Bakersfield, CA\
August 2022 - August 2023

- Installed residential solar energy systems in a team of 6
- Implemented and utilized monitoring software for energy systems to diagnose and troubleshoot performance
- Communicated with clients to deliver focused solutions
- Adhered to strict build protocol and regulations to promote strict quality control 

#### University Exam Proctor
BYU-Idaho, Rexburg, ID\
May 2024 - Present

- Administer and manage tests of dozens of students daily
- Comply with standard operating procedures to protect testing integrity and accurate file management
- Interact with database front end interface to manage student and test information

---

### Skills

Python: Pandas, NumPy, Scikit-learn, Plotly Express | R: ggplot, mosaic, tidyverse, R-markdown | SQL: SQLite, MySQL, ERDs | Hypothesis mesting | Statistical modeling | Data visualization | Data wrangling | Effective communication | Team collaboration | Problem-solving | Quality control

<a href='project_files/resume_draft_2.pdf' target='_blank'><h3>Click here to download this resume</h3></a>